### ISSUE TITLE
doggo does not build van Apple M1 monterey using golang 1.18

### ISSUE THREAD

**Issue by githubkarel** [mr-karan/doggo#34]
The problem reported when installing:
go install github.com/mr-karan/doggo/cmd/doggo@latest
go: downloading github.com/mr-karan/doggo v0.5.0
go: downloading github.com/fatih/color v1.10.0
go: downloading github.com/miekg/dns v1.1.40
go: downloading github.com/knadh/koanf v0.14.0
go: downloading github.com/sirupsen/logrus v1.7.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/ameshkov/dnsstamps v1.0.3
go: downloading github.com/olekukonko/tablewriter v0.0.4
go: downloading github.com/ameshkov/dnscrypt/v2 v2.2.1
go: downloading github.com/lucas-clemente/quic-go v0.24.0
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading golang.org/x/sys v0.0.0-20210510120138-977fb7262007
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading golang.org/x/net v0.0.0-20210428140749-89ef3d95e781
go: downloading github.com/mitchellh/mapstructure v1.2.2
go: downloading github.com/AdguardTeam/golibs v0.4.2
go: downloading github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: downloading github.com/aead/poly1305 v0.0.0-20180717145839-3fee0db0b635
go: downloading github.com/cheekybits/genny v1.0.0
go: downloading github.com/marten-seemann/qtls-go1-17 v0.1.0
# github.com/lucas-clemente/quic-go/internal/qtls
go/pkg/mod/github.com/lucas-clemente/quic-go@v0.24.0/internal/qtls/go118.go:6:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration

**Comment by mr-karan** [comment]
Seems similar to https://github.com/mr-karan/doggo/issues/33 ? 

Can you try building from latest HEAD?

**Comment by gonejack** [comment]
Have no issue doing a `git clone` and `go build github.com/mr-karan/doggo/cmd/doggo` on my M1 machine

**Comment by githubkarel** [comment]
Indeed confirmed. Doing the local build works like a charm.

**Comment by mr-karan** [comment]
Ah, understood. This issue is coming, because I erroneously pushed a `0.5.0` tag. When doing a `go mod install`, the `@latest` seems to be picking that up, when it should be picking `0.4.2`. 

I'm not exactly sure how do I make this tag go away in `pkg.go.dev`: https://pkg.go.dev/github.com/mr-karan/doggo

**Comment by mr-karan** [comment]
Since Go module versions are [immutable](https://stackoverflow.com/questions/68955904/remove-old-versions-from-pkg-go-dev), I think I should have used `retract` instead of deleting the tag. This is a TIL for me.

I'll publish 0.5.1 in sometime after working on a pending feature, for now please clone & build.  Keeping the issue open until then

Thanks!

**Comment by mr-karan** [comment]
Released a new version: https://github.com/mr-karan/doggo/issues/35

Closing this, as it should be fine now.

```
go install github.com/mr-karan/doggo/cmd/doggo@latest
go: downloading github.com/mr-karan/doggo v0.5.1
```
