### ISSUE TITLE
doggo should only query one resolver by default

### ISSUE THREAD

**Issue by sekrause** [mr-karan/doggo#35]
When your operating system is using multiple resolvers, doggo sends the query to all of them and shows the result for each resolver. This makes simple, quick hostname lookups much harder to read because the output is basically duplicated.

For example in my network the same nameserver can be reached over IPv4 and IPv6, so I _always_ get two rows for each DNS record. This makes doggo uncomfortable to use.

I think doggo should only use _one_ resolver unless I explicitly pass arguments to doggo telling it to use multiple resolvers.

**Comment by mr-karan** [comment]
No, I think the current implementation is correct. `dig` chooses one resolver randomly and you won't know which one unless you read the whole output. I want `doggo` to act in the most deterministic way possible, no surprises for the end user.

If you want to query a single nameserver, you can always do that with `@`.

**Comment by pinkiepiemeetsrainbowdash** [comment]
@mr-karan I see your point, but I actually agree with @sekrause that it is not practical to always type @servername to get a quick resolve. There should be at least an option to query just one DNS server (first one or random one or both options) available to the user. Also, it would be nice to have a file like ~/.doggo.rc to put all needed options, like dig has ~/.digrc. Otherwise kudos to developer, nice job!

P.S. One more note - doggo output is wider than dig and this breaks results on narrower terminals. It would be nice to have an option to narrow the available output (maybe DNS resolver address not needed if we already specify @ option?). This narrow option could be also used in ~/.doggo.rc for people who want dig-like output.

**Comment by mr-karan** [comment]
> There should be at least an option to query just one DNS server (first one or random one or both options) available to the user

Ah yeah. This makes sense, I can make it configurable, the default however will be to query all. :+1: 

> Also, it would be nice to have a file like ~/.doggo.rc to put all needed options, like dig has ~/.digrc

I'd thought about it too, will explore :) 

> This narrow option could be also used in ~/.doggo.rc for people who want dig-like output

Yeah, I can remove the `nameserver` field in `--narrow` but then again, the terminal windows can be resized even smaller which would break. Maybe it makes sense to add an option similar to `dig +x` here instead.

**Comment by pinkiepiemeetsrainbowdash** [comment]
Indeed! For the terminal window, the width of the output depends on the length of the record queried, of course, but for the dig it is usually less than 100 symbols and often even less than 80. That fits to the default terminal size for most distros, so this is something a future --narrow option could aim for :)

**Comment by mr-karan** [comment]
Released a new version: https://github.com/mr-karan/doggo/issues/35

```
./bin/doggo.bin mrkaran.dev --strategy=<first|random|all>
```

It's set to `all` to maintain backward compatibility. 

In addition, have added a `--short` flag too for just emitting the `answer` section like `dig`.

Please feel free to re-open in case I missed something. Thanks!
