### ISSUE TITLE
Feature request: need option to specific ip of DoH

### ISSUE THREAD

**Issue by issuex** [mr-karan/doggo#56]
If i query to `https://cloudflare-dns.com/dns-query`. Is it possible to specific ip for `cloudflare-dns.com` to some `xxx.xxx.xxx.xxx` ip?
In `https://github.com/ameshkov/dnslookup` have feture to specific  ip for it. It's really good to have this feature in some use case.

**Comment by mr-karan** [comment]
What is the usecase for this?

**Comment by issuex** [comment]
- When dns server respond wrong ip of `cloudflare-dns.com` or was blocked.
- When you don't want to leak dns query to ISP.
- etc, that why `https://github.com/ameshkov/dnslookup` have this feature.

**Comment by mr-karan** [comment]
> When dns server respond wrong ip of cloudflare-dns.com or was blocked.

This seems like a very rare scenario. How would you get the IP of `cloudflare-dns.com` if not without DNS? :smile: 

> When you don't want to leak dns query to ISP.

How does using an IP instead of a hostname for the resolver prevent a leak? You'd rather use DoH if that is your usecase.

I'll have to close this for now. Will revisit if there's an actual usecase for this.

**Comment by issuex** [comment]
If you stay in high censorship country, You will need it.
